[package]
name = "hub"
version = "0.1.0"
edition = "2018"

[dependencies]
util = { package = "webrtc-util", version = "0.5.4", default-features = false, features = [
    "conn"
] }
dtls = { package = "webrtc-dtls", path = "../../" }
tokio = { version = "1.19", features = ["full"] }
x509-parser = "0.13.0"
rcgen = { version = "0.9.2", features = ["pem", "x509-parser"] }
ring = "0.16.19"
rustls = "0.19.0"
log = "0.4"
thiserror = "1.0"
